image: ultainfinity-wallet-website

pipelines:
  branches: # Branch-specific pipelines definitions
    develop:
      - step:
          name: Build and test the app
          image: node:latest
          script:
            - npm install
            - npm run test
            - npm run build
  # default:
  custom:
    Staging:
      - step:
          name: Production Build App
          image: node:latest
          script:
            - npm install
            - npm run build
          artifacts:
            - build/**
      - step:
          name: Deploying the app to S3
          deployment: Staging
          script:
            - pipe: atlassian/aws-s3-deploy:0.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET # uiw-web
                ACL: 'public-read'
                LOCAL_PATH: 'build'
