image: ultainfinity-wallet-website

pipelines:
  branches: # Branch-specific pipelines definitions
    master:
      - step:
          name: Build and test the app
          image: node:latest
          script:
            - npm install
            - npm run test
            - npm run build
  # default:
  # custom: