export const GET_ASSETS = 'ulta-cards/currencies/GET_ASSETS'
export const GET_ASSETS_SUCCESS = 'ulta-cards/currencies/GET_ASSETS_SUCCESS'
export const IS_ASSETS_FETCHING = 'ulta-cards/currencies/IS_ASSETS_FETCHING'
export const GET_ASSETS_DATA_SUCCESS = 'ulta-cards/currencies/GET_ASSETS_DATA_SUCCESS'
export const GET_ASSETS_DATA = 'ulta-cards/currencies/GET_ASSETS_DATA'
export const GET_ASSETS_DATA_ARRAY_SUCCESS = 'ulta-cards/currencies/GET_ASSETS_DATA_ARRAY_SUCCESS'