export const SET_STATUS_OPTIONS = 'ulta-cards/userSettings/SET_STATUS_OPTIONS'
export const SET_TARIFF_OPTIONS = 'ulta-cards/userSettings/SET_TARIFF_OPTIONS'
export const SET_TYPE_OPTIONS = 'ulta-cards/userSettings/SET_TYPE_OPTIONS'
export const SET_STATUS_OPTIONS_SUCCESS = 'ulta-cards/userSettings/SET_STATUS_OPTIONS_SUCCESS'
export const SET_TARIFF_OPTIONS_SUCCESS = 'ulta-cards/userSettings/SET_TARIFF_OPTIONS_SUCCESS'
export const SET_TYPE_OPTIONS_SUCCESS = 'ulta-cards/userSettings/SET_TYPE_OPTIONS_SUCCESS'
